### ISSUE TITLE
search with serial number

### ISSUE THREAD

**Issue by siba65** [kuehne-trustable-de/ca3sCore#393]
With the serial number you can only search with a decimal value, not with a hexadecimal value.
Unless you know that hexadecimal must be preceded by 0x. The user should be informed of this in an info box

**Comment by kuehne-trustable-de** [comment]
Alternatively it could find all variants at once. '12' would match decimal '12' and hexadecimal '12' (decimal '18').

Would this behaviour be convenient or irritating?

**Comment by kuehne-trustable-de** [comment]
The 'all at once' search mode would be useful only for 'equals'. It may return wrong results for 'bigger than' and 'less than'.
Going to implement the proposed info box

**Comment by kuehne-trustable-de** [comment]
Fixed in version 1.0.0
