### ISSUE TITLE
Use of the values "not like" or "not equal" when searching in the data fields "PKI Level" and "Issuer"

### ISSUE THREAD

**Issue by siba65** [kuehne-trustable-de/ca3sCore#487]
A search in the field "Issuer" with the value "not like" or "not equal" does not generate a hit. The search with the value "like" or "equal" works.
Also a search in the field "PKI Level" with the value "not like" or "not equal" does not return a hit.

**Comment by kuehne-trustable-de** [comment]
Behaviour fixed in version 1.1.7
